apiVersion: v1
kind: Secret
metadata:
  name: db-user-env-variables
type: Opaque
stringData:
  DB_USER: "<nom d'utilisateur du novel utilisateur>"
  DB_PASSWORD: "<mot de pass du nouvel utilisateur>"
  MARIADB_ROOT_PASSWORD: "<mot de passe de l'utilisateur root>"
  DB_NAME: "<nom de base de donnee>"