apiVersion: apps/v1 # Deployment Info
kind: Deployment
metadata:
  name: mariadb-deployment
spec: # Deployment Characteristics
  replicas: 4
  selector:
    matchLabels:
      app: mariadb
  template: # Pod Template and Characteristics
    metadata:
      labels:
        app: mariadb
    spec:
      containers: # Container Characteristics
      - name: acme_database
        image: mariadb:11.8
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ALLOW_EMPTY_ROOT_PASSWORD
          value: "0"
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-env-variables
              key: MARIADB_ROOT_PASSWORD
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: db-user-env-variables
              key: DB_USER
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-user-env-variables
              key: DB_PASSWORD
---
apiVersion: apps/v1 # Service Info
kind: Service
metadata:
  name: mariadb-service
spec:
  type: NodePort # Have no clue what this is ?: Exposes Services
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port : 3306
      targetPort: 3306
      nodePort: 3306